apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirqab-relay

resources:
  - namespace.yaml
  - configmap.yaml
  - network-policy.yaml
  - deployments/http-c2.yaml

commonLabels:
  app.kubernetes.io/part-of: mirqab
  app.kubernetes.io/managed-by: kustomize
