apiVersion: v2
name: cloud-relay
description: OffenSight Cloud Relay - Adversary Infrastructure Simulation
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - offensight
  - security
  - adversary-simulation
  - c2
  - phishing

maintainers:
  - name: OffenSight Team
    email: support@offensight.io

dependencies:
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
